# This file is autogenerated by nixos-generate-config during installation.
# You should run nixos-generate-config and replace this file with the generated one.
# This is a placeholder to allow flake evaluation during development.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # This is a placeholder - replace with actual hardware configuration
  # after running: nixos-generate-config --root /mnt
  
  # Expected configuration for UM790 Pro:
  # - AMD Ryzen 9 7940HS CPU
  # - Integrated AMD Radeon 780M graphics
  # - AMD microcode updates
  # - NVMe storage support
  # - USB 3.x/4.0 support
  # - Modern networking (WiFi 6E, etc.)

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # CPU microcode
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Note: Actual filesystem configuration is handled by disko.nix
  # The installer will generate the proper fileSystems entries

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}